# The URL the site will be built for
base_url = "https://zola.trewhitt.se"

# Site title — available in templates as {{ config.title }}
title = "My Zola Site"

# Site description — available in templates as {{ config.description }}
description = "A fast static site built with Zola and Tailwind CSS."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[[taxonomies]]
name = "tags"
url = "tags"
feed = true

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
